server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /ecb-rates {
        proxy_pass https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
